# Generated by Django 2.1.5 on 2019-02-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20190211_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='help',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
